import Head from 'next/head'
import Image from 'next/image'
import ReactFullpage from '@fullpage/react-fullpage';
import Button from '../components/Button';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Facundo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ReactFullpage
    //fullpage options
    licenseKey = {'YOUR_KEY_HERE'}
    scrollingSpeed = {1000} /* Options here */

    render={({ state, fullpageApi }) => {
      return (
        <ReactFullpage.Wrapper>
          <div className="section ">

            <div className=' h-1/2 relative'>
            <Image
              width={900}
              height={700}
              alt="goku"
              src="/images/goku1.jpg"
              layout="fill"
              objectFit='cover'
              />

            </div>

            <h2 className=' text-7xl'>Hola,<br/> soy Goku...</h2>



              <div className=' text-center mb-[20vh]'>
                  <ButtonDown  onClick={() => fullpageApi.moveSectionDown()}>
                  &#x25BC;
                  </ButtonDown>
              </div>










          </div>
          <div className="section">
            <p>Section 2</p>
          </div>
        </ReactFullpage.Wrapper>
      );
    }}
  />


    </div>
  )
}


const ButtonDown = ({children, onClick})=>  <button className='text-3xl mx-auto inline-block bg-yellow-500 px-8 py-4 border-8 border-gray-900'  onClick={ onClick }>
{children}
</button>