import Head from 'next/head'
import Image from 'next/image'
import ReactFullpage from '@fullpage/react-fullpage';
import Button from '../components/Button';
import ReactAudioPlayer from 'react-audio-player';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Facundo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=' max-w-xl mx-auto shadow-sm shadow-black'>
      <ReactFullpage
        //fullpage options
        licenseKey = {'YOUR_KEY_HERE'}
        scrollingSpeed = {1000} /* Options here */

        render={({ state, fullpageApi }) => {
          return (
            <ReactFullpage.Wrapper>
              <div className="section !flex flex-col ">

                <div className=' h-1/2 relative'>
                <Image
                  width={900}
                  height={700}
                  alt="goku"
                  src="/images/goku1.jpg"
                  layout="fill"
                  objectFit='cover'
                  />

                </div>
                <div className='px-14'>
                  <h2 className=' text-8xl'>Hola,<br/> soy Goku...</h2>
                </div>


                  <div className='absolute bottom-10 w-full text-center '>
                    <h5 className='text-2xl'>Seguí bajando che gil</h5>
                      <ButtonDown  onClick={() => fullpageApi.moveSectionDown()}>
                      &#x25BC;
                      </ButtonDown>
                  </div>

              </div>
              <div className="section !flex flex-col ">
                <div className=' h-[300px] relative'>
                  <Image
                    width={900}
                    height={700}
                    alt="goku"
                    src="/images/striper.jpg"
                    layout="fill"
                    objectFit='cover'
                    />

                  </div>
                  <div className='px-14 pt-8'>
                    <h2 className=' text-8xl'>¿Que pasa<br/> maraca?</h2>
                    <h4 className='text-4xl mt-8'>No se si sabras pero se viene  mi cumple. <br/>
                    Y vamo a festejarlo como corresponde.

                    </h4>

                  </div>
                  <div className='absolute bottom-10 w-full text-center '>
                    <h5 className='text-2xl'>Seguí bajando (puto el que lee)</h5>
                      <ButtonDown  onClick={() => fullpageApi.moveSectionDown()}>
                      &#x25BC;
                      </ButtonDown>
                  </div>
              </div>
              <div className="section !flex flex-col bg-yellow-300 ">

                  <div className='px-14 pt-8'>
                    <h2 className=' text-6xl'>Super guitarreada en mi casa</h2>
                    <div className=' h-[300px] relative my-8'>
                  <Image
                    width={900}
                    height={700}
                    alt="goku"
                    src="/images/goku2.jpg"
                    layout="fill"
                    objectFit='cover'
                    />

                  </div>
                    <h4 className='text-4xl mt-8'>Pero para para para...<br/>
                    Todavía no estás invitado.

                    </h4>

                  </div>
                  <div className='absolute bottom-10 w-full text-center '>
                    <h5 className='text-2xl'>Ver requisitos</h5>
                      <ButtonDown  onClick={() => fullpageApi.moveSectionDown()}>
                      &#x25BC;
                      </ButtonDown>
                  </div>
              </div>
              <div className="section !flex flex-col bg-black text-white ">

                  <div className='px-14 pt-24'>
                   <ul className=' text-4xl'>
                    <li>Tocas algun instrumento?</li>
                    <li>Cantas?</li>
                    <li>Cebas Fernet?</li>
                    <li>Me quieres?</li>
                    <li>Te cuartearon mas de una vez?</li>
                   </ul>

                   <h4 className=' text-yellow-300 text-4xl mt-14'>
                   Si contestaste si a todas, Felicitaciones estas invitado!!!
                   </h4>

                  </div>
                  <div className='absolute bottom-10 w-full text-center '>
                    <h5 className='text-2xl'>Ver donde y cuando</h5>
                      <ButtonDown  onClick={() => fullpageApi.moveSectionDown()}>
                      &#x25BC;
                      </ButtonDown>
                  </div>
              </div>
              <div className="section !flex flex-col ">

                  <div className='px-14 pt-24'>
                   <h3 className=' text-6xl'>Sábado 21/5 <br/> al mediodía</h3>
                   <h2 className=' text-yellow-300 text-9xl'>Locro Libre</h2>
                    <ReactAudioPlayer
                      src="audio/invitacion.ogg"
                      autoPlay={true}
                      controls
                    />
                   <h5 className=' text-4xl my-8'>No falles, no seas mandao</h5>
                   <a href='https://goo.gl/maps/FQmtoxuUDZyo8Y5y7'  target="_blank" rel="noreferrer" ><ButtonDown>Ver ubicación en mapa</ButtonDown></a>
                   <a arget="_blank"  target="_blank" rel="noreferrer"  href="https://wa.me/+5493855759961?text=Claro que voy che gil">
                     <ButtonDown>Confirmar presencia</ButtonDown>
                   </a>

                  </div>

              </div>
            </ReactFullpage.Wrapper>
          );
        }}
      />

      </div>



    </div>
  )
}


const ButtonDown = ({children, onClick})=>  <button className='text-3xl mx-auto inline-block bg-yellow-300 px-8 py-4 border-8 border-gray-900'  onClick={ onClick }>
{children}
</button>